import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
const Random = () => {
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>{router.query.random}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Page: {router.query.random}
    </div>
  );
};

export default Random;
